# from flask import Flask, render_template
# from models import db  # Ensure models.py is correct
# from flask_sqlalchemy import SQLAlchemy
# from functions import load_snps_from_csv

# # Initialize the Flask app
# app = Flask(__name__)

# # Configuration
# app.config['SECRET_KEY'] = 'your_secret_key'
# app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
# app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# # Initialize the database with Flask
# db.init_app(app)

# # Import routes AFTER initializing db to avoid circular imports
# from routes import *

# # Create database tables if they don’t exist
# with app.app_context():
#     db.create_all()

# # Load SNP data into the database from the CSV generated by data.py


# if __name__ == '__main__':
#     load_snps_from_csv("snps_with_positions.csv")
#     app.run(debug=True)


from flask import Flask
from models import db, SNP  # Import SNP model for database checks
from functions import load_snps_from_csv

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = 'your_secret_key'

# Initialize database
db.init_app(app)

# Import routes AFTER initializing db
from routes import *

# Create tables and load data
with app.app_context():
    db.create_all()
    
    # Load data only if the SNP table is empty
    if not SNP.query.first():
        load_snps_from_csv("DATA/SEC_DATA.csv")

if __name__ == '__main__':
    app.run(debug=True)
